aerokube/moon-website

src/css/imports/style.scss
webpack.common.js

Correctly rendering images from CSS

---

site/config.toml

Better title and description

---

src/index.js

Correctly printing license generation error

---

site/data/meta.json
site/layouts/404.html

Better 404 page and one more article

---

webpack.common.js

Correct syntax to update copy-webpack-plugin to 6.0

---

webpack.common.js
webpack.dev.js
webpack.prod.js

Changes to be compatible with new css-loader and webpack-merge versions

---

site/config.toml
site/data/meta.json
site/layouts/index.html
site/layouts/partials/assistance.html
src/css/imports/style.scss

Added Moon assistance program section

---

site/layouts/index.html
site/layouts/partials/cloud.html
src/css/imports/style.scss

Added Moon cloud section

---

site/data/meta.json

Added new article about Moon and CDP

---

site/data/meta.json

Added Moon Cloud article

---

package-lock.json
package.json

Fixed webpack build

---

site/data/meta.json

Added article about Selenium Grid 4

---

deploy.sh
site/data/meta.json

Browsers -> Moon Cloud

---

site/data/meta.json
site/layouts/partials/menu.html

Added blog.aerokube.com

---

site/data/meta.json

Added Moon 2 article

---

site/data/meta.json

Added Moon context article

---

package-lock.json
src/range.js

Showing More instead of Unlimited in range

---

site/data/meta.json

Added security article

---

site/config.toml
site/data/meta.json
site/layouts/partials/cloud.html
site/layouts/partials/hero.html

Updates for Moon Cloud website changes

---

site/data/meta.json

Updated Youtube channel URL

---

.github/workflows/build.yml
site/data/meta.json
site/layouts/index.html
site/layouts/partials/feedback.html

fix: delete free-trial request button
